# Generated by Django 3.2.5 on 2021-07-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.CharField(blank=True, max_length=255, null=True)),
                ('incident_date', models.CharField(blank=True, max_length=255, null=True)),
                ('incident_time', models.CharField(blank=True, max_length=255, null=True)),
                ('reported_date', models.CharField(blank=True, max_length=255, null=True)),
                ('reported_time', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('incident_type', models.CharField(blank=True, max_length=255, null=True)),
                ('hyperlinks', models.CharField(blank=True, max_length=255, null=True)),
                ('incident_details', models.TextField(blank=True, null=True)),
                ('suspect_descriptions', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'incidents',
                'managed': False,
            },
        ),
    ]
